version: '3'

networks:
  event_hub_network:
    driver: bridge

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: [ "sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m flask run --no-debugger --no-reload --host ${APPLICATION_HOST} --port ${APPLICATION_PORT}" ]
    ports:
      - "${APPLICATION_PORT}:${APPLICATION_PORT}"
      - "5678:5678"
    networks:
      - event_hub_network
    volumes:
      - .:/event-hub-backend
    environment:
      - APPLICATION_HOST=$APPLICATION_HOST
      - APPLICATION_PORT=$APPLICATION_PORT
      - DB_DRIVER=$DB_DRIVER
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - TWITCH_CLIENT_ID=$TWITCH_CLIENT_ID
      - TWITCH_CLIENT_SECRET=$TWITCH_CLIENT_SECRET
      - TWITCH_REDIRECT_URI=$TWITCH_REDIRECT_URI
      - FLASK_APP=$FLASK_APP
      - FLASK_ENV=$FLASK_ENV

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_NAME
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - event_hub_network
    volumes:
      - ./scripts/database:/docker-entrypoint-initdb.d
