version: '3'

networks:
  event_hub_network:
    driver: bridge

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m flask run --no-debugger --no-reload --host 0.0.0.0 --port 5000"]
    ports:
      - 5000:5000
      - 5678:5678
    networks:
      - event_hub_network
    volumes:
      - .:/event-hub-backend
    environment:
      - FLASK_APP=wsgi.py
      - FLASK_ENV=development
      - APPLICATION_HOST=0.0.0.0

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: event_hub
    ports:
      - "3306:3306"
    networks:
      - event_hub_network
    volumes:
      - ./scripts/database:/docker-entrypoint-initdb.d
